config/routes.rb
Rails.application.routes.draw do

  get 'standrds/index'

  get 'standrds/new'

  get 'stds/index'

  get 'stds/new'

  get 'students/new'

  get 'students/index'

  get 'issues/new'

  get 'issues/index'

  get 'issues/show'

  get 'issues/destroy'

  get 'issues/update'

  devise_for :users, path: '',path_names: {sign_in: 'login', sign_out: "logout",sign_up: 'join-us'}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'home#index'
    end
  end
  resources :users
  resources :issues
  resources :stds
  get 'switch_user' => 'switch_user#set_current_user'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
	belongs_to :user
end

app/models/issues.rb
class Issues < ActiveRecord::Base
end

app/models/standrd.rb
class Standrd < ActiveRecord::Base
end

app/models/std.rb
class Std < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :issues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name , :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name , :email, :password, :password_confirmation, :current_password)
    end
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authenticate_user!
  def index
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  def new
  end
  def index
    @issues = current_user.issues
  end

  def show
  end

  def destroy
  end

  def update
  end

  private
    def user_params
      params.require(:issue).permit(:email, :content, :status, :url, :user_id, :id) 
    end
end

app/controllers/standrds_controller.rb
class StandrdsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/stds_controller.rb
class StdsController < ApplicationController
  def index
  	@students = Std.all
  end

  def new
  	@student = Std.new
  end

  def create
  	Std.create(std_params)
  	# return render json: params.inspect
  	redirect_to stds_path
  end

  def edit
  	@std = Std.find(params[:id])	
  end

  def update
  	
  end

  private
  	def std_params
      params.require(:std).permit(:name, :sirname, :dob, :gender, :contact, :classes, :email)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  	@student = Std.new
  end

  def create
  	
  end

  def index
  	@students = Student.all
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	if user_signed_in? && current_user.role == 'admin'
  		@users = User.where('role !=?', 'admin')
  	else
  		flash[:alert] = "Access Denied!"
  		redirect_to root_path
  	end
  end

  def show
  	if user_signed_in? && current_user.role == 'admin'
  		@user = User.find(params[:id])
  	else
  		flash[:alert] = "Access Denied!"
  		redirect_to root_path
  	end
  end
  def destroy
  	@user = User.find(params[:id])
  	if @user.destroy!
  		flash[:notice] = "User Deleted Successfully"
  		redirect_to users_path
  	end
  	
  end

  private
  	def user_params
  		params.require(:user).permit(:email, :password, :current_password, :password_confirmation, :name, :id) 
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/standrds_helper.rb
module StandrdsHelper
end

app/helpers/stds_helper.rb
module StdsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/standrds/index.html.erb
<h1>Standrds#index</h1>
<p>Find me in app/views/standrds/index.html.erb</p>

app/views/standrds/new.html.erb
<h1>Standrds#new</h1>
<p>Find me in app/views/standrds/new.html.erb</p>

app/views/stds/index.html.erb
<script type="text/javascript">
	var d = document.getElementById("student");
	d.className = d.className + " active";
</script>

<h1>Users</h1>
<br/><br/>
	<table class="table table-striped" style=" width: 900px;">
		<thead style="background:#666; color:white;">
		    <tr>
		      	<th>Name</th>
		        <th>Email</th>
		        <th>Father Name</th>
		        <th>Class</th>
		      	<th colspan="3" style="text-align:center;">Action</th>
		    </tr>
		</thead>
		
		<tbody>
		    <% @students.each do |userA| %>
		      <tr>
		        <td>
		        	<%= link_to "#{userA.try(:name)}", std_path(userA) %>
		        </td>
		        <td>
		        	<%= userA.try(:email) %>
		        </td>
		        <td>
		        	<%= userA.sirname %>
		        </td>
		        <td>
		        	<%= userA.classes %>
		        </td>
		        <td>
		        	<%= link_to 'Delete', '/stds/'+userA.id.to_s, method: :delete, data: { confirm: 'Are you sure?' }, :title => "Delete #{userA.try(:name)} account", :class => 'btn btn-mini btn-danger', :style => 'font-size:8.6px;margin-right:-25px;' %>
		        </td>
		        <td>
		        	<%# if userA.confirmed_at.present? %>
		        		<%#= link_to 'SU',"/switch_user?scope_identifier=user_#{userA.random_key}", :title => "Switch to #{userA.try(:uname)} account", :class => 'btn btn-mini', :style => 'font-size:8.6px;margin-right:-25px;background-color:black;color:white' %>
		        	<%# else %>
		        	<%#= link_to 'SU',"javascript:void(0);", :title => "User not confirmed yet...", :class => 'btn btn-mini', :style => 'font-size:8.6px;margin-right:-25px;background-color:#9C9C9C;color:white' %>
		        	<%# end %>
		        </td>
		        
		      </tr>
		    <% end %>
		  </tbody>
	</table>

app/views/stds/new.html.erb
<script type="text/javascript">
  var d = document.getElementById("join");
  d.className = d.className + " active";
</script>

<div class="container">  
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">Sign Up</h1>
      <div class="account-wall">
        <%= form_for @student do |f| %>
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true ,class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :father_name %>
            <%= f.text_field :sirname,class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :class %>
            <%= f.text_field :classes ,type: 'number',class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :date_of_birth %>
            <%= f.text_field :dob ,class: "form-control" %>
          </div>
          
          <div class="field">
            <%= f.label :gender %>
            <%= f.text_field :gender ,class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :contact %>
            <%= f.text_field :contact ,class: "form-control" %>
          </div>

          <br>
          <div class="actions">
            <%= f.submit "Add Student", class: "btn btn-block btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<script type="text/javascript">
	var d = document.getElementById("student");
	d.className = d.className + " active";
</script>

<h1>Users</h1>
<br/><br/>
	<table class="table table-striped" style=" width: 900px;">
		<thead style="background:#666; color:white;">
		    <tr>
		      	<th>Name</th>
		        <th>Email</th>
		        <th>Class</th>
		        <th>Address</th>
		      	<th>Last Signed In At</th>
		      	<th>Created At</th>

		      	<th colspan="3" style="text-align:center;">Action</th>
		    </tr>
		</thead>
		
		<tbody>
		    <% @students.each do |userA| %>
		      <tr>
		        <td>
		        	<%= link_to "#{userA.try(:name)}", student_path(userA) %>
		        </td>
		        <td>
		        	<%= userA.try(:email) %>
		        </td>
		        <td>
		        	<%= userA.last_sign_in_at %>
		        </td>
		        <td>
		        	<%= userA.created_at.to_s %>
		        </td>
		        <td>
		        	<%= link_to 'Delete', '/students/'+userA.id.to_s, method: :delete, data: { confirm: 'Are you sure?' }, :title => "Delete #{userA.try(:name)} account", :class => 'btn btn-mini btn-danger', :style => 'font-size:8.6px;margin-right:-25px;' %>
		        </td>
		        <td>
		        	<%# if userA.confirmed_at.present? %>
		        		<%#= link_to 'SU',"/switch_user?scope_identifier=user_#{userA.random_key}", :title => "Switch to #{userA.try(:uname)} account", :class => 'btn btn-mini', :style => 'font-size:8.6px;margin-right:-25px;background-color:black;color:white' %>
		        	<%# else %>
		        	<%#= link_to 'SU',"javascript:void(0);", :title => "User not confirmed yet...", :class => 'btn btn-mini', :style => 'font-size:8.6px;margin-right:-25px;background-color:#9C9C9C;color:white' %>
		        	<%# end %>
		        </td>
		        
		      </tr>
		    <% end %>
		  </tbody>
	</table>

app/views/students/new.html.erb
<script type="text/javascript">
  var d = document.getElementById("join");
  d.className = d.className + " active";
</script>

<div class="container">  
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">Sign Up</h1>
      <div class="account-wall">
        <%= form_for @student do |f| %>
          <div class="field">
            <%= f.label :name %><br/>
            <%= f.text_field :name, autofocus: true ,class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :fathername %><br/>
            <%= f.text_field :sirname,class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :class %><br/>
            <%= f.text_field :class ,type: 'number',class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :dateofbirth %><br />
            <%= f.email_field :dob ,class: "form-control" %>
          </div>
          
          <div class="field">
            <%= f.label :gender %><br />
            <%= f.email_field :gender ,class: "form-control" %>
          </div>

          <div class="field">
            <%= f.label :contact %><br />
            <%= f.email_field :contact ,class: "form-control" %>
          </div>

          <br>
          <div class="actions">
            <%= f.submit "Add Student", class: "btn btn-block btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>