config/routes.rb
Rails.application.routes.draw do

  get 'standrds/index'

  get 'standrds/new'

  get 'stds/index'

  get 'stds/new'

  get 'students/new'

  get 'students/index'

  get 'issues/new'

  get 'issues/index'

  get 'issues/show'

  get 'issues/destroy'

  get 'issues/update'

  devise_for :users, path: '',path_names: {sign_in: 'login', sign_out: "logout",sign_up: 'join-us'}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'home#index'
    end
  end
  resources :users
  resources :issues
  resources :stds
  get 'switch_user' => 'switch_user#set_current_user'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
	belongs_to :user
end

app/models/issues.rb
class Issues < ActiveRecord::Base
end

app/models/standrd.rb
class Standrd < ActiveRecord::Base
end

app/models/std.rb
class Std < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :issues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name , :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name , :email, :password, :password_confirmation, :current_password)
    end
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authenticate_user!
  def index
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  def new
  end
  def index
    @issues = current_user.issues
  end

  def show
  end

  def destroy
  end

  def update
  end

  private
    def user_params
      params.require(:issue).permit(:email, :content, :status, :url, :user_id, :id) 
    end
end

app/controllers/standrds_controller.rb
class StandrdsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/stds_controller.rb
class StdsController < ApplicationController
  def index
  	@students = Std.all
  end

  def new
  	@student = Std.new
  end

  def create
  	Std.create(std_params)
  	# return render json: params.inspect
  	redirect_to stds_path
  end

  def edit
  	@std = Std.find(params[:id])	
  end

  def update
  	
  end

  private
  	def std_params
      params.require(:std).permit(:name, :sirname, :dob, :gender, :contact, :classes, :email)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  	@student = Std.new
  end

  def create
  	
  end

  def index
  	@students = Student.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	if user_signed_in? && current_user.role == 'admin'
  		@users = User.where('role !=?', 'admin')
  	else
  		flash[:alert] = "Access Denied!"
  		redirect_to root_path
  	end
  end

  def show
  	if user_signed_in? && current_user.role == 'admin'
  		@user = User.find(params[:id])
  	else
  		flash[:alert] = "Access Denied!"
  		redirect_to root_path
  	end
  end
  def destroy
  	@user = User.find(params[:id])
  	if @user.destroy!
  		flash[:notice] = "User Deleted Successfully"
  		redirect_to users_path
  	end
  	
  end

  private
  	def user_params
  		params.require(:user).permit(:email, :password, :current_password, :password_confirmation, :name, :id) 
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/standrds_helper.rb
module StandrdsHelper
end

app/helpers/stds_helper.rb
module StdsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>CRM</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%#= stylesheet_link_tag "theme/bootstrap.css" %>
    <%#= stylesheet_link_tag "theme/usebootstrap.css" %>
	  <%= csrf_meta_tags %>
	</head>
	<body class="<%= params[:controller] %>">
		<!-- Nav bar start-->
		<div class="navbar navbar-default navbar-fixed-top" style="background:#1b1e24">
      <div class="container">
        <div class="navbar-header" >
          <a href="<%= authenticated_root_path %>" class="navbar-brand">Faisal School System</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
				  <ul class="nav navbar-nav">
				  	<% if user_signed_in? %>
			        <li>
			          <a href="javascript:void(0);">Issues Reported</a>
			        </li>
			        <li>
			          <a href="javascript:void(0);">Features</a>
			        </li>
			      <% end %>
			      <% if user_signed_in? && current_user.role == 'admin'%>
				      <li class = '', id = 'user'>
				      	<a href='<%= users_path %>'>Users</a>
				      </li>
				      <li class = '', id = 'student'>
				      	<a href='<%= stds_path %>'>Students</a>
				      </li>

				    <% end %>
				  </ul>
				  <ul class="nav navbar-nav navbar-right">
					  <% if user_signed_in? %>
					    <li class='' id='edit'style="color:white;"><%= link_to "#{ current_user.name }", edit_user_registration_path %></li>
					    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
					  <% else %>
					    <li class='' id='login'> <%= link_to "Log In", new_user_session_path %> </li>
					    <li class='' id='join'> <%= link_to "Join Us", new_user_registration_path %></li>
					  <% end %>
				  </ul>
        </div>
      </div>
    </div>
  	<div class="col-xs-6 col-md-3" style="margin-top: 62px; margin-left: -15px;width:20%;float:left; height: 550px; position:fixed;"> 
	  	<div class="page-sidebar" id="main-menu"> 
			  	
			  	<!-- END MINI-PROFILE -->

			  	<!-- BEGIN SIDEBAR MENU -->	
				  <ul>	
			      <li class=""> 
			      	<a href="<%= root_path %>"> 
			      		<i class="icon-custom-home"></i> 
			      		<span class="title">Dashboard</span> 
			      		<span class="selected"></span>
			      	</a> 
			      </li>
			      <hr/>
				  	<li class="" id="issue"> 
				  		<a href="<%= issues_path %>"> 
				  			<i class="fa fa-envelope"></i> 
				  			<span class="title">Issues Reported</span>
				  		</a> 
				  	</li>
				  	<hr/>      
				  	<li class=""> 
				  		<a href="../frontend/index.html"> 
				  			<i class="fa fa-flag"></i>  
				  			<span class="title">Frontend</span>
				  		</a>
				  	</li> 
				  	<li class=""> 
				  		<a href="../frontend/index.html"> 
				  			<i class="fa fa-flag"></i>  
				  			<span class="title">UI Elements</span>
				  		</a>
				  	</li> 
				  	<li class=""> 
				  		<a href="../frontend/index.html"> 
				  			<i class="fa fa-flag"></i>  
				  			<span class="title">Forums</span>
				  		</a>
				  	</li>      
			      <!-- <li class=""> 
			      	<a href="javascript:;"> 
			      		<i class="icon-custom-ui"></i> 
			      		<span class="title">UI Elements</span> 
			      		<span class="arrow "></span> 
			      	</a>
			        <ul class="sub-menu">
					  		<li > 
					  			<a href="typography.html"> Typography </a> 
					  		</li>
					  		<li > 
					  			<a href="messages_notifications.html"> Messages & Notifications </a> 
					  		</li>
					   		<li > 
					   			<a href="icons.html">Icons</a> 
					   		</li>
					   		<li > 
					   			<a href="buttons.html">Buttons</a> 
					   		</li>		 
			          <li > 
			          	<a href="tabs_accordian.html"> Tabs & Accordions </a> 
			          </li>
			          <li > 
			          	<a href="sliders.html">Sliders</a> 
			          </li>
			          <li > 
			          	<a href="group_list.html">Group list </a> 
			          </li>
			        </ul>
			      </li>
				  	<li class=""> 
				  		<a href="javascript:;"> 
				  			<i class="icon-custom-form"></i> 
				  			<span class="title">Forms</span> 
				  			<span class="arrow "></span> 
				  		</a>
			        <ul class="sub-menu">
			          <li > 
			          	<a href="form_elements.html">Form Elements </a> 
			          </li>
			          <li > 
			          	<a href="form_validations.html">Form Validations</a> 
			          </li>
			        </ul>
			      </li>
				  	<li class="hidden-lg hidden-md hidden-xs" id="more-widgets" > 
				  		<a href="javascript:;"> 
				  			<i class="fa fa-plus"></i>
				  		</a> 
					  	<ul class="sub-menu">
					  		<li class="side-bar-widgets">
									<p class="menu-title">
										FOLDER 
										<span class="pull-right">
											<a href="#" class="create-folder">
												<i class="icon-plus"></i>
											</a>
										</span>
									</p>
									<ul class="folders" >
							  		<li>
							  			<a href="#">
							  				<div class="status-icon green"></div> My quick tasks 
							  			</a> 
							  		</li>
							  		<li>
							  			<a href="#">
							  				<div class="status-icon red"></div> To do list 
							  			</a> 
							  		</li>
							  		<li>
							  			<a href="#">
							  				<div class="status-icon blue"></div> Projects 
							  			</a> 
							  		</li>
							  		<li class="folder-input" style="display:none">
							  			<input type="text" placeholder="Name of folder" class="no-boarder folder-name" name="" id="folder-name" />
							  		</li>
									</ul>
									<p class="menu-title">PROJECTS </p>
									<div class="status-widget">
										<div class="status-widget-wrapper">
											<div class="title">Freelancer
												<a href="#" class="remove-widget">
													<i class="icon-custom-cross"></i>
												</a>
											</div>
											<p>Redesign home page</p>
										</div>
									</div>
									<div class="status-widget">
										<div class="status-widget-wrapper">
											<div class="title">envato
												<a href="#" class="remove-widget">
													<i class="icon-custom-cross"></i>
												</a>
											</div>
											<p>Statistical report</p>
										</div>
									</div>
								</li>
							</ul>
				  	</li>  -->   
			    </ul>
					<!-- <div class="side-bar-widgets">
						<p class="menu-title" style= "margin-left:10px;">FOLDER 
							<span class="pull-right">
								<a href="#" class="create-folder"> 
									<i class="fa fa-plus"></i>
								</a>
							</span>
						</p>
						<ul class="folders" >
					  	<li>
					  		<a href="#">
					  			<div class="status-icon green"></div> My quick tasks 
					  		</a> 
					  	</li>
					  	<li>
					  		<a href="#">
					  			<div class="status-icon red"></div> To do list 
					  		</a> 
					  	</li>
					  	<li>
					  		<a href="#">
					  			<div class="status-icon blue"></div> Projects 
					  		</a> 
					  	</li>
					  	<li class="folder-input" style="display:none">
					  		<input type="text" placeholder="Name of folder" class="no-boarder folder-name" name="" />
					  	</li>
						</ul>
					</div> -->
					<a href="#" class="scrollup">Scroll</a>
					<div class="clearfix"></div>
			    <!-- END SIDEBAR MENU --> 
			 </div>
		</div>

    <!-- nav bar end -->
		<div class = "content">
			<div class="container" style ="margin-top:70px; width:80%;float:right !important;">
				<!-- flash display start -->
				<% flash.each do |name, msg| %>
					  <% if msg.is_a?(String) %>
					    <% name = name.to_s == 'success' ? 'success' : name.to_s %>
					    <% name = name.to_s == 'alert' ? 'danger' : name.to_s %>
					  <% name = name.to_s == 'notice' ? 'info' : name.to_s %>    
				    <div class="alert alert-<%= name %> main-alert">
				      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
				    </div>
				  <% end %>
				<% end %>
				<!-- flash display end -->
	    	<%= yield %>
	  	</div>
		</div>
	</body>
</html>